- name: Create .pub files in a directory
  hosts: localhost
  vars:
    project: "{{ project }}"
    filename: "{{ filename }}"
  tasks:
  - name: Create local file with info
    lineinfile:
      path: "/home/{{ project }}/{{ filename }}.pub"
      line: "{{ key }}"
      state: present
      create: true
