- name: Create .pub files in a directory
  hosts: localhost
  vars:
    project: "{{ project }}"
    filename: "{{ filename }}"
  tasks:
  - name: Check if the file exists
    stat:
      path: "/home/{{ project }}/{{ filename }}.pub"
    register: file_check
  - name: Create a local file with info
    lineinfile:
      path: "/home/{{ project }}/{{ filename }}.pub"
      line: "{{ key }}"
      state: present
      create: true
    when: not file_check.stat.exists
  - name: Return a message if the file already exists
    debug:
      msg: "The file already exists and no content was written."
    when: file_check.stat.exists
