---
- name: Manage SSH keys on remote servers
  hosts: all
  become: yes
  tasks:

    - name: Add the selected SSH key
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ key }}.pub') }}"
