- name: List .pub files in a directory
  hosts: localhost
  tasks:
    - name: Find all .pub files in the specified directory
      find:
        paths: "/home"   # Specify the directory to search in
        patterns: "*.pub"             # Only look for .pub files
        recurse: yes                  # Set to yes if you want to search subdirectories
      register: pub_files             # Register the result to use later

    - name: Display the clean list of .pub files
      debug:
        msg: | "{{ pub_files.files | map(attribute='path') | map('basename') | join('\n') }}"
