- name: List .pub files in a directory
  hosts: localhost
  tasks:
    - name: Find all .pub files in the specified directory
      find:
        paths: "/home"   # Specify the directory to search in
        patterns: "*.pub"             # Only look for .pub files
        recurse: yes                  # Set to yes if you want to search subdirectories
      register: pub_files             # Register the result to use later

    - name: Format the list as numbered output
      set_fact:
        numbered_keys: "{{ numbered_keys|default([]) + ['%d. %s' % (item|int + 1, pub_files.files[item].path | basename)] }}"
      loop: "{{ range(0, pub_files.files|length) }}"

    - name: Display the clean numbered list of .pub files
      debug:
        msg: "{{ numbered_keys | join('\n') }}"
