---
- name: Manage SSH keys on remote servers
  hosts: all
  become: yes
  tasks:

    - name: List available SSH keys
      debug:
        msg: "Key"
      loop: "{% for key in query('fileglob', '/home/*.pub') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
