- name: List .pub files in a directory
  hosts: localhost
  tasks:
    - name: Find all .pub files in the specified directory
      find:
        paths: "/home"   # Specify the directory to search in
        patterns: "*.pub"             # Only look for .pub files
        recurse: yes                  # Set to yes if you want to search subdirectories
      register: pub_files             # Register the result to use later

    - name: Format and display the numbered list
      set_fact:
        numbered_keys: "{{ numbered_keys | default([]) + ['%d. %s' % (item.0 + 1, item.1.path | basename)] }}"
      with_indexed_items: "{{ pub_files.files }}"

    - name: Display the clean numbered list of .pub files in a single message
      debug:
        msg: "{{ numbered_keys | join('\n') }}"
