---
- name: Manage SSH keys on remote servers
  hosts: all
  become: yes
  tasks:
    - name: Add SSH key for a user (if not already present)
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ ssh_key }}"
